# /codespace/contentai/docker-compose.yml
version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    image: geauxacademy.azurecr
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/contentai
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: